name: restaurantsapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_fonts: ^2.0.0
  scratcher: ^2.1.0
  fl_chart: ^0.36.2
  pin_code_fields: ^7.2.0
  get_storage: ^2.0.2
 

 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#42a5f5"
  image: assets/icons/logo.png
  
  

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

